# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99832a2281fe95b26d9b4e0f9cd2e89b9aa8d5219255ca7b789520fe1c0ab3b3293df9eaa697ac9d90dbc7923d579838832d1f2a4cbce3b5c48b12f9a5dfb44b

test:
  secret_key_base: 15a522d8d8e78fc4c79a5518a4d995c4e74f302a66cb0e0bf3f96d37b3ec81f961b9b74ab8d03a8a8f90db96ce89ed1191c5dec649ac724e1de27713bb84702f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
